image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/ui-autotesting:node-browsers node-browsers/
    - docker build -t $CI_REGISTRY_IMAGE/ui-autotesting:alpine-php7 alpine-php7/
    - docker push $CI_REGISTRY_IMAGE/ui-autotesting:node-browsers
    - docker push $CI_REGISTRY_IMAGE/ui-autotesting:alpine-php7
