all: php*/Dockerfile alpine*/Dockerfile

DEPS = Dockerfile.template composer.json start.sh

php7/Dockerfile: $(DEPS)
	sed -e 1i'# This file is autogenerated from Makefile' \
	    -e 's!$$$$PHP_VERSION!7.3-cli!' \
	    -e 's!$$$$PHPUNIT_VERSION!8.2.4!' Dockerfile.template >| php7/Dockerfile
	cp composer.json start.sh php7/

alpine-php7/Dockerfile: $(DEPS)
	sed -e 1i'# This file is autogenerated from Makefile' \
	    -e 's!$$$$PHP_VERSION!7!g' \
	    -e 's!$$$$PHPUNIT_VERSION!8.2.4!' Dockerfile.alpine.template >| alpine-php7/Dockerfile
